[package]
name = "workflow"
version = "0.1.0"
edition = "2024"

[dependencies]
proto = { path = "../proto" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["sync"] }
tracing = "0.1"
