/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { EFFECT_REWARDS_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const INIT_DISCRIMINATOR = new Uint8Array([
  220, 59, 207, 236, 108, 250, 47, 100,
]);

export function getInitDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(INIT_DISCRIMINATOR);
}

export type InitInstruction<
  TProgram extends string = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
  TAccountReflectionAccount extends string | IAccountMeta<string> = string,
  TAccountRewardVaultTokenAccount extends
    | string
    | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountMint extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountRent extends
    | string
    | IAccountMeta<string> = 'SysvarRent111111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountReflectionAccount extends string
        ? WritableAccount<TAccountReflectionAccount>
        : TAccountReflectionAccount,
      TAccountRewardVaultTokenAccount extends string
        ? WritableAccount<TAccountRewardVaultTokenAccount>
        : TAccountRewardVaultTokenAccount,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts,
    ]
  >;

export type InitInstructionData = { discriminator: ReadonlyUint8Array };

export type InitInstructionDataArgs = {};

export function getInitInstructionDataEncoder(): Encoder<InitInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: INIT_DISCRIMINATOR })
  );
}

export function getInitInstructionDataDecoder(): Decoder<InitInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getInitInstructionDataCodec(): Codec<
  InitInstructionDataArgs,
  InitInstructionData
> {
  return combineCodec(
    getInitInstructionDataEncoder(),
    getInitInstructionDataDecoder()
  );
}

export type InitAsyncInput<
  TAccountReflectionAccount extends string = string,
  TAccountRewardVaultTokenAccount extends string = string,
  TAccountAuthority extends string = string,
  TAccountMint extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  reflectionAccount?: Address<TAccountReflectionAccount>;
  rewardVaultTokenAccount?: Address<TAccountRewardVaultTokenAccount>;
  authority: TransactionSigner<TAccountAuthority>;
  mint: Address<TAccountMint>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
};

export async function getInitInstructionAsync<
  TAccountReflectionAccount extends string,
  TAccountRewardVaultTokenAccount extends string,
  TAccountAuthority extends string,
  TAccountMint extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
>(
  input: InitAsyncInput<
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountAuthority,
    TAccountMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  InitInstruction<
    TProgramAddress,
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountAuthority,
    TAccountMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_REWARDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    reflectionAccount: {
      value: input.reflectionAccount ?? null,
      isWritable: true,
    },
    rewardVaultTokenAccount: {
      value: input.rewardVaultTokenAccount ?? null,
      isWritable: true,
    },
    authority: { value: input.authority ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.reflectionAccount.value) {
    accounts.reflectionAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([114, 101, 102, 108, 101, 99, 116, 105, 111, 110])
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.rewardVaultTokenAccount.value) {
    accounts.rewardVaultTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.reflectionAccount.value)
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      'SysvarRent111111111111111111111111111111111' as Address<'SysvarRent111111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.reflectionAccount),
      getAccountMeta(accounts.rewardVaultTokenAccount),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.rent),
    ],
    programAddress,
    data: getInitInstructionDataEncoder().encode({}),
  } as InitInstruction<
    TProgramAddress,
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountAuthority,
    TAccountMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >;

  return instruction;
}

export type InitInput<
  TAccountReflectionAccount extends string = string,
  TAccountRewardVaultTokenAccount extends string = string,
  TAccountAuthority extends string = string,
  TAccountMint extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  reflectionAccount: Address<TAccountReflectionAccount>;
  rewardVaultTokenAccount: Address<TAccountRewardVaultTokenAccount>;
  authority: TransactionSigner<TAccountAuthority>;
  mint: Address<TAccountMint>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
};

export function getInitInstruction<
  TAccountReflectionAccount extends string,
  TAccountRewardVaultTokenAccount extends string,
  TAccountAuthority extends string,
  TAccountMint extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
>(
  input: InitInput<
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountAuthority,
    TAccountMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress }
): InitInstruction<
  TProgramAddress,
  TAccountReflectionAccount,
  TAccountRewardVaultTokenAccount,
  TAccountAuthority,
  TAccountMint,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountRent
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_REWARDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    reflectionAccount: {
      value: input.reflectionAccount ?? null,
      isWritable: true,
    },
    rewardVaultTokenAccount: {
      value: input.rewardVaultTokenAccount ?? null,
      isWritable: true,
    },
    authority: { value: input.authority ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      'SysvarRent111111111111111111111111111111111' as Address<'SysvarRent111111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.reflectionAccount),
      getAccountMeta(accounts.rewardVaultTokenAccount),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.rent),
    ],
    programAddress,
    data: getInitInstructionDataEncoder().encode({}),
  } as InitInstruction<
    TProgramAddress,
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountAuthority,
    TAccountMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >;

  return instruction;
}

export type ParsedInitInstruction<
  TProgram extends string = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    reflectionAccount: TAccountMetas[0];
    rewardVaultTokenAccount: TAccountMetas[1];
    authority: TAccountMetas[2];
    mint: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
    tokenProgram: TAccountMetas[5];
    rent: TAccountMetas[6];
  };
  data: InitInstructionData;
};

export function parseInitInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedInitInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      reflectionAccount: getNextAccount(),
      rewardVaultTokenAccount: getNextAccount(),
      authority: getNextAccount(),
      mint: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getInitInstructionDataDecoder().decode(instruction.data),
  };
}
