/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from '@solana/kit';
import { EFFECT_REWARDS_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const SYNC_DISCRIMINATOR = new Uint8Array([
  4, 219, 40, 164, 21, 157, 189, 88,
]);

export function getSyncDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(SYNC_DISCRIMINATOR);
}

export type SyncInstruction<
  TProgram extends string = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
  TAccountStakeAccount extends string | IAccountMeta<string> = string,
  TAccountRewardAccount extends string | IAccountMeta<string> = string,
  TAccountStakeVaultTokenAccount extends string | IAccountMeta<string> = string,
  TAccountReflectionAccount extends string | IAccountMeta<string> = string,
  TAccountStakeProgram extends
    | string
    | IAccountMeta<string> = 'effSujUiy4eT2vrMqSsUkb6oT3C7pC42UnWSukRpu5e',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountStakeAccount extends string
        ? ReadonlyAccount<TAccountStakeAccount>
        : TAccountStakeAccount,
      TAccountRewardAccount extends string
        ? WritableAccount<TAccountRewardAccount>
        : TAccountRewardAccount,
      TAccountStakeVaultTokenAccount extends string
        ? ReadonlyAccount<TAccountStakeVaultTokenAccount>
        : TAccountStakeVaultTokenAccount,
      TAccountReflectionAccount extends string
        ? WritableAccount<TAccountReflectionAccount>
        : TAccountReflectionAccount,
      TAccountStakeProgram extends string
        ? ReadonlyAccount<TAccountStakeProgram>
        : TAccountStakeProgram,
      ...TRemainingAccounts,
    ]
  >;

export type SyncInstructionData = { discriminator: ReadonlyUint8Array };

export type SyncInstructionDataArgs = {};

export function getSyncInstructionDataEncoder(): Encoder<SyncInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: SYNC_DISCRIMINATOR })
  );
}

export function getSyncInstructionDataDecoder(): Decoder<SyncInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getSyncInstructionDataCodec(): Codec<
  SyncInstructionDataArgs,
  SyncInstructionData
> {
  return combineCodec(
    getSyncInstructionDataEncoder(),
    getSyncInstructionDataDecoder()
  );
}

export type SyncAsyncInput<
  TAccountStakeAccount extends string = string,
  TAccountRewardAccount extends string = string,
  TAccountStakeVaultTokenAccount extends string = string,
  TAccountReflectionAccount extends string = string,
  TAccountStakeProgram extends string = string,
> = {
  stakeAccount: Address<TAccountStakeAccount>;
  rewardAccount?: Address<TAccountRewardAccount>;
  stakeVaultTokenAccount?: Address<TAccountStakeVaultTokenAccount>;
  reflectionAccount: Address<TAccountReflectionAccount>;
  stakeProgram?: Address<TAccountStakeProgram>;
};

export async function getSyncInstructionAsync<
  TAccountStakeAccount extends string,
  TAccountRewardAccount extends string,
  TAccountStakeVaultTokenAccount extends string,
  TAccountReflectionAccount extends string,
  TAccountStakeProgram extends string,
  TProgramAddress extends Address = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
>(
  input: SyncAsyncInput<
    TAccountStakeAccount,
    TAccountRewardAccount,
    TAccountStakeVaultTokenAccount,
    TAccountReflectionAccount,
    TAccountStakeProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  SyncInstruction<
    TProgramAddress,
    TAccountStakeAccount,
    TAccountRewardAccount,
    TAccountStakeVaultTokenAccount,
    TAccountReflectionAccount,
    TAccountStakeProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_REWARDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    stakeAccount: { value: input.stakeAccount ?? null, isWritable: false },
    rewardAccount: { value: input.rewardAccount ?? null, isWritable: true },
    stakeVaultTokenAccount: {
      value: input.stakeVaultTokenAccount ?? null,
      isWritable: false,
    },
    reflectionAccount: {
      value: input.reflectionAccount ?? null,
      isWritable: true,
    },
    stakeProgram: { value: input.stakeProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.rewardAccount.value) {
    accounts.rewardAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.stakeAccount.value)),
      ],
    });
  }
  if (!accounts.stakeVaultTokenAccount.value) {
    accounts.stakeVaultTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.stakeAccount.value)),
      ],
    });
  }
  if (!accounts.stakeProgram.value) {
    accounts.stakeProgram.value =
      'effSujUiy4eT2vrMqSsUkb6oT3C7pC42UnWSukRpu5e' as Address<'effSujUiy4eT2vrMqSsUkb6oT3C7pC42UnWSukRpu5e'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.stakeAccount),
      getAccountMeta(accounts.rewardAccount),
      getAccountMeta(accounts.stakeVaultTokenAccount),
      getAccountMeta(accounts.reflectionAccount),
      getAccountMeta(accounts.stakeProgram),
    ],
    programAddress,
    data: getSyncInstructionDataEncoder().encode({}),
  } as SyncInstruction<
    TProgramAddress,
    TAccountStakeAccount,
    TAccountRewardAccount,
    TAccountStakeVaultTokenAccount,
    TAccountReflectionAccount,
    TAccountStakeProgram
  >;

  return instruction;
}

export type SyncInput<
  TAccountStakeAccount extends string = string,
  TAccountRewardAccount extends string = string,
  TAccountStakeVaultTokenAccount extends string = string,
  TAccountReflectionAccount extends string = string,
  TAccountStakeProgram extends string = string,
> = {
  stakeAccount: Address<TAccountStakeAccount>;
  rewardAccount: Address<TAccountRewardAccount>;
  stakeVaultTokenAccount: Address<TAccountStakeVaultTokenAccount>;
  reflectionAccount: Address<TAccountReflectionAccount>;
  stakeProgram?: Address<TAccountStakeProgram>;
};

export function getSyncInstruction<
  TAccountStakeAccount extends string,
  TAccountRewardAccount extends string,
  TAccountStakeVaultTokenAccount extends string,
  TAccountReflectionAccount extends string,
  TAccountStakeProgram extends string,
  TProgramAddress extends Address = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
>(
  input: SyncInput<
    TAccountStakeAccount,
    TAccountRewardAccount,
    TAccountStakeVaultTokenAccount,
    TAccountReflectionAccount,
    TAccountStakeProgram
  >,
  config?: { programAddress?: TProgramAddress }
): SyncInstruction<
  TProgramAddress,
  TAccountStakeAccount,
  TAccountRewardAccount,
  TAccountStakeVaultTokenAccount,
  TAccountReflectionAccount,
  TAccountStakeProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_REWARDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    stakeAccount: { value: input.stakeAccount ?? null, isWritable: false },
    rewardAccount: { value: input.rewardAccount ?? null, isWritable: true },
    stakeVaultTokenAccount: {
      value: input.stakeVaultTokenAccount ?? null,
      isWritable: false,
    },
    reflectionAccount: {
      value: input.reflectionAccount ?? null,
      isWritable: true,
    },
    stakeProgram: { value: input.stakeProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.stakeProgram.value) {
    accounts.stakeProgram.value =
      'effSujUiy4eT2vrMqSsUkb6oT3C7pC42UnWSukRpu5e' as Address<'effSujUiy4eT2vrMqSsUkb6oT3C7pC42UnWSukRpu5e'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.stakeAccount),
      getAccountMeta(accounts.rewardAccount),
      getAccountMeta(accounts.stakeVaultTokenAccount),
      getAccountMeta(accounts.reflectionAccount),
      getAccountMeta(accounts.stakeProgram),
    ],
    programAddress,
    data: getSyncInstructionDataEncoder().encode({}),
  } as SyncInstruction<
    TProgramAddress,
    TAccountStakeAccount,
    TAccountRewardAccount,
    TAccountStakeVaultTokenAccount,
    TAccountReflectionAccount,
    TAccountStakeProgram
  >;

  return instruction;
}

export type ParsedSyncInstruction<
  TProgram extends string = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    stakeAccount: TAccountMetas[0];
    rewardAccount: TAccountMetas[1];
    stakeVaultTokenAccount: TAccountMetas[2];
    reflectionAccount: TAccountMetas[3];
    stakeProgram: TAccountMetas[4];
  };
  data: SyncInstructionData;
};

export function parseSyncInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedSyncInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      stakeAccount: getNextAccount(),
      rewardAccount: getNextAccount(),
      stakeVaultTokenAccount: getNextAccount(),
      reflectionAccount: getNextAccount(),
      stakeProgram: getNextAccount(),
    },
    data: getSyncInstructionDataDecoder().decode(instruction.data),
  };
}
