/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from '@solana/kit';
import { EFFECT_REWARDS_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const TOPUP_DISCRIMINATOR = new Uint8Array([
  126, 42, 49, 78, 225, 151, 99, 77,
]);

export function getTopupDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(TOPUP_DISCRIMINATOR);
}

export type TopupInstruction<
  TProgram extends string = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountReflectionAccount extends string | AccountMeta<string> = string,
  TAccountRewardVaultTokenAccount extends string | AccountMeta<string> = string,
  TAccountIntermediateRewardVaultTokenAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountMint extends string
        ? WritableAccount<TAccountMint>
        : TAccountMint,
      TAccountReflectionAccount extends string
        ? WritableAccount<TAccountReflectionAccount>
        : TAccountReflectionAccount,
      TAccountRewardVaultTokenAccount extends string
        ? WritableAccount<TAccountRewardVaultTokenAccount>
        : TAccountRewardVaultTokenAccount,
      TAccountIntermediateRewardVaultTokenAccount extends string
        ? WritableAccount<TAccountIntermediateRewardVaultTokenAccount>
        : TAccountIntermediateRewardVaultTokenAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type TopupInstructionData = { discriminator: ReadonlyUint8Array };

export type TopupInstructionDataArgs = {};

export function getTopupInstructionDataEncoder(): FixedSizeEncoder<TopupInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: TOPUP_DISCRIMINATOR })
  );
}

export function getTopupInstructionDataDecoder(): FixedSizeDecoder<TopupInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getTopupInstructionDataCodec(): FixedSizeCodec<
  TopupInstructionDataArgs,
  TopupInstructionData
> {
  return combineCodec(
    getTopupInstructionDataEncoder(),
    getTopupInstructionDataDecoder()
  );
}

export type TopupAsyncInput<
  TAccountMint extends string = string,
  TAccountReflectionAccount extends string = string,
  TAccountRewardVaultTokenAccount extends string = string,
  TAccountIntermediateRewardVaultTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  mint: Address<TAccountMint>;
  reflectionAccount?: Address<TAccountReflectionAccount>;
  rewardVaultTokenAccount?: Address<TAccountRewardVaultTokenAccount>;
  intermediateRewardVaultTokenAccount?: Address<TAccountIntermediateRewardVaultTokenAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getTopupInstructionAsync<
  TAccountMint extends string,
  TAccountReflectionAccount extends string,
  TAccountRewardVaultTokenAccount extends string,
  TAccountIntermediateRewardVaultTokenAccount extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
>(
  input: TopupAsyncInput<
    TAccountMint,
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountIntermediateRewardVaultTokenAccount,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  TopupInstruction<
    TProgramAddress,
    TAccountMint,
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountIntermediateRewardVaultTokenAccount,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_REWARDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    mint: { value: input.mint ?? null, isWritable: true },
    reflectionAccount: {
      value: input.reflectionAccount ?? null,
      isWritable: true,
    },
    rewardVaultTokenAccount: {
      value: input.rewardVaultTokenAccount ?? null,
      isWritable: true,
    },
    intermediateRewardVaultTokenAccount: {
      value: input.intermediateRewardVaultTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.reflectionAccount.value) {
    accounts.reflectionAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([114, 101, 102, 108, 101, 99, 116, 105, 111, 110])
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.rewardVaultTokenAccount.value) {
    accounts.rewardVaultTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.reflectionAccount.value)
        ),
      ],
    });
  }
  if (!accounts.intermediateRewardVaultTokenAccount.value) {
    accounts.intermediateRewardVaultTokenAccount.value =
      await getProgramDerivedAddress({
        programAddress,
        seeds: [
          getAddressEncoder().encode(
            expectAddress(accounts.rewardVaultTokenAccount.value)
          ),
        ],
      });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.reflectionAccount),
      getAccountMeta(accounts.rewardVaultTokenAccount),
      getAccountMeta(accounts.intermediateRewardVaultTokenAccount),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getTopupInstructionDataEncoder().encode({}),
  } as TopupInstruction<
    TProgramAddress,
    TAccountMint,
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountIntermediateRewardVaultTokenAccount,
    TAccountTokenProgram
  >;

  return instruction;
}

export type TopupInput<
  TAccountMint extends string = string,
  TAccountReflectionAccount extends string = string,
  TAccountRewardVaultTokenAccount extends string = string,
  TAccountIntermediateRewardVaultTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  mint: Address<TAccountMint>;
  reflectionAccount: Address<TAccountReflectionAccount>;
  rewardVaultTokenAccount: Address<TAccountRewardVaultTokenAccount>;
  intermediateRewardVaultTokenAccount: Address<TAccountIntermediateRewardVaultTokenAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getTopupInstruction<
  TAccountMint extends string,
  TAccountReflectionAccount extends string,
  TAccountRewardVaultTokenAccount extends string,
  TAccountIntermediateRewardVaultTokenAccount extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
>(
  input: TopupInput<
    TAccountMint,
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountIntermediateRewardVaultTokenAccount,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): TopupInstruction<
  TProgramAddress,
  TAccountMint,
  TAccountReflectionAccount,
  TAccountRewardVaultTokenAccount,
  TAccountIntermediateRewardVaultTokenAccount,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_REWARDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    mint: { value: input.mint ?? null, isWritable: true },
    reflectionAccount: {
      value: input.reflectionAccount ?? null,
      isWritable: true,
    },
    rewardVaultTokenAccount: {
      value: input.rewardVaultTokenAccount ?? null,
      isWritable: true,
    },
    intermediateRewardVaultTokenAccount: {
      value: input.intermediateRewardVaultTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.reflectionAccount),
      getAccountMeta(accounts.rewardVaultTokenAccount),
      getAccountMeta(accounts.intermediateRewardVaultTokenAccount),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getTopupInstructionDataEncoder().encode({}),
  } as TopupInstruction<
    TProgramAddress,
    TAccountMint,
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountIntermediateRewardVaultTokenAccount,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ParsedTopupInstruction<
  TProgram extends string = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    mint: TAccountMetas[0];
    reflectionAccount: TAccountMetas[1];
    rewardVaultTokenAccount: TAccountMetas[2];
    intermediateRewardVaultTokenAccount: TAccountMetas[3];
    tokenProgram: TAccountMetas[4];
  };
  data: TopupInstructionData;
};

export function parseTopupInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedTopupInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      mint: getNextAccount(),
      reflectionAccount: getNextAccount(),
      rewardVaultTokenAccount: getNextAccount(),
      intermediateRewardVaultTokenAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getTopupInstructionDataDecoder().decode(instruction.data),
  };
}
