version: "3.8"

services:
  manager:
    image: jhamer/effect-manager:latest
    restart: unless-stopped
    ports:
      - "8888:8888"
    expose:
      - "34859"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - manager
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
