version: "3.8"

services:
  validator:
    image: anzaxyz/agave:stable
    command: solana-test-validator --quiet
    ports:
      - "8899:8899"
      - "8900:8900"
    networks:
      - solana
    volumes:
      - solana-validator:/root/.config/solana
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000

  anchor:
    image: solanafoundation/anchor:v0.31.1
    working_dir: /app/solana
    command: ./scripts/deploy.sh
    depends_on:
      - validator
    volumes:
      - .:/app
    environment:
      - ANCHOR_PROVIDER_URL=http://validator:8899
    networks:
      - solana

networks:
  solana:

volumes:
  solana-validator:
