packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'patches/*'
  - 'environments/*'
  - 'docs'
  - 'website'
  - 'solana'
  # exclude packages that are inside test directories
  - '!**/test/**'
