packages:
  # all packages in direct subdirs of packages/
  - "packages/**"
  # all apps in direct subdirs of apps/
  - "apps/**"
  - "modules/**"
  - "services/**"
  - "core/**"
  - "tools/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
