/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { EFFECT_PAYMENT_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const CREATE_PAYMENT_POOL_DISCRIMINATOR = new Uint8Array([
  39, 242, 23, 233, 229, 198, 28, 204,
]);

export function getCreatePaymentPoolDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_PAYMENT_POOL_DISCRIMINATOR
  );
}

export type CreatePaymentPoolInstruction<
  TProgram extends string = typeof EFFECT_PAYMENT_PROGRAM_ADDRESS,
  TAccountPaymentAccount extends string | AccountMeta<string> = string,
  TAccountPaymentVaultTokenAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountUserTokenAccount extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountRent extends
    | string
    | AccountMeta<string> = 'SysvarRent111111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPaymentAccount extends string
        ? WritableSignerAccount<TAccountPaymentAccount> &
            AccountSignerMeta<TAccountPaymentAccount>
        : TAccountPaymentAccount,
      TAccountPaymentVaultTokenAccount extends string
        ? WritableAccount<TAccountPaymentVaultTokenAccount>
        : TAccountPaymentVaultTokenAccount,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountUserTokenAccount extends string
        ? WritableAccount<TAccountUserTokenAccount>
        : TAccountUserTokenAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts,
    ]
  >;

export type CreatePaymentPoolInstructionData = {
  discriminator: ReadonlyUint8Array;
  managerAuthority: Address;
  amount: bigint;
};

export type CreatePaymentPoolInstructionDataArgs = {
  managerAuthority: Address;
  amount: number | bigint;
};

export function getCreatePaymentPoolInstructionDataEncoder(): FixedSizeEncoder<CreatePaymentPoolInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['managerAuthority', getAddressEncoder()],
      ['amount', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CREATE_PAYMENT_POOL_DISCRIMINATOR })
  );
}

export function getCreatePaymentPoolInstructionDataDecoder(): FixedSizeDecoder<CreatePaymentPoolInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['managerAuthority', getAddressDecoder()],
    ['amount', getU64Decoder()],
  ]);
}

export function getCreatePaymentPoolInstructionDataCodec(): FixedSizeCodec<
  CreatePaymentPoolInstructionDataArgs,
  CreatePaymentPoolInstructionData
> {
  return combineCodec(
    getCreatePaymentPoolInstructionDataEncoder(),
    getCreatePaymentPoolInstructionDataDecoder()
  );
}

export type CreatePaymentPoolAsyncInput<
  TAccountPaymentAccount extends string = string,
  TAccountPaymentVaultTokenAccount extends string = string,
  TAccountAuthority extends string = string,
  TAccountMint extends string = string,
  TAccountUserTokenAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  paymentAccount: TransactionSigner<TAccountPaymentAccount>;
  paymentVaultTokenAccount?: Address<TAccountPaymentVaultTokenAccount>;
  authority: TransactionSigner<TAccountAuthority>;
  mint: Address<TAccountMint>;
  userTokenAccount: Address<TAccountUserTokenAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
  managerAuthority: CreatePaymentPoolInstructionDataArgs['managerAuthority'];
  amount: CreatePaymentPoolInstructionDataArgs['amount'];
};

export async function getCreatePaymentPoolInstructionAsync<
  TAccountPaymentAccount extends string,
  TAccountPaymentVaultTokenAccount extends string,
  TAccountAuthority extends string,
  TAccountMint extends string,
  TAccountUserTokenAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof EFFECT_PAYMENT_PROGRAM_ADDRESS,
>(
  input: CreatePaymentPoolAsyncInput<
    TAccountPaymentAccount,
    TAccountPaymentVaultTokenAccount,
    TAccountAuthority,
    TAccountMint,
    TAccountUserTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  CreatePaymentPoolInstruction<
    TProgramAddress,
    TAccountPaymentAccount,
    TAccountPaymentVaultTokenAccount,
    TAccountAuthority,
    TAccountMint,
    TAccountUserTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_PAYMENT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    paymentAccount: { value: input.paymentAccount ?? null, isWritable: true },
    paymentVaultTokenAccount: {
      value: input.paymentVaultTokenAccount ?? null,
      isWritable: true,
    },
    authority: { value: input.authority ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    userTokenAccount: {
      value: input.userTokenAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.paymentVaultTokenAccount.value) {
    accounts.paymentVaultTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.paymentAccount.value)
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      'SysvarRent111111111111111111111111111111111' as Address<'SysvarRent111111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.paymentAccount),
      getAccountMeta(accounts.paymentVaultTokenAccount),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.userTokenAccount),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.rent),
    ],
    data: getCreatePaymentPoolInstructionDataEncoder().encode(
      args as CreatePaymentPoolInstructionDataArgs
    ),
    programAddress,
  } as CreatePaymentPoolInstruction<
    TProgramAddress,
    TAccountPaymentAccount,
    TAccountPaymentVaultTokenAccount,
    TAccountAuthority,
    TAccountMint,
    TAccountUserTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >);
}

export type CreatePaymentPoolInput<
  TAccountPaymentAccount extends string = string,
  TAccountPaymentVaultTokenAccount extends string = string,
  TAccountAuthority extends string = string,
  TAccountMint extends string = string,
  TAccountUserTokenAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  paymentAccount: TransactionSigner<TAccountPaymentAccount>;
  paymentVaultTokenAccount: Address<TAccountPaymentVaultTokenAccount>;
  authority: TransactionSigner<TAccountAuthority>;
  mint: Address<TAccountMint>;
  userTokenAccount: Address<TAccountUserTokenAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
  managerAuthority: CreatePaymentPoolInstructionDataArgs['managerAuthority'];
  amount: CreatePaymentPoolInstructionDataArgs['amount'];
};

export function getCreatePaymentPoolInstruction<
  TAccountPaymentAccount extends string,
  TAccountPaymentVaultTokenAccount extends string,
  TAccountAuthority extends string,
  TAccountMint extends string,
  TAccountUserTokenAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof EFFECT_PAYMENT_PROGRAM_ADDRESS,
>(
  input: CreatePaymentPoolInput<
    TAccountPaymentAccount,
    TAccountPaymentVaultTokenAccount,
    TAccountAuthority,
    TAccountMint,
    TAccountUserTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress }
): CreatePaymentPoolInstruction<
  TProgramAddress,
  TAccountPaymentAccount,
  TAccountPaymentVaultTokenAccount,
  TAccountAuthority,
  TAccountMint,
  TAccountUserTokenAccount,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountRent
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_PAYMENT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    paymentAccount: { value: input.paymentAccount ?? null, isWritable: true },
    paymentVaultTokenAccount: {
      value: input.paymentVaultTokenAccount ?? null,
      isWritable: true,
    },
    authority: { value: input.authority ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    userTokenAccount: {
      value: input.userTokenAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      'SysvarRent111111111111111111111111111111111' as Address<'SysvarRent111111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.paymentAccount),
      getAccountMeta(accounts.paymentVaultTokenAccount),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.userTokenAccount),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.rent),
    ],
    data: getCreatePaymentPoolInstructionDataEncoder().encode(
      args as CreatePaymentPoolInstructionDataArgs
    ),
    programAddress,
  } as CreatePaymentPoolInstruction<
    TProgramAddress,
    TAccountPaymentAccount,
    TAccountPaymentVaultTokenAccount,
    TAccountAuthority,
    TAccountMint,
    TAccountUserTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >);
}

export type ParsedCreatePaymentPoolInstruction<
  TProgram extends string = typeof EFFECT_PAYMENT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    paymentAccount: TAccountMetas[0];
    paymentVaultTokenAccount: TAccountMetas[1];
    authority: TAccountMetas[2];
    mint: TAccountMetas[3];
    userTokenAccount: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
    rent: TAccountMetas[7];
  };
  data: CreatePaymentPoolInstructionData;
};

export function parseCreatePaymentPoolInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCreatePaymentPoolInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      paymentAccount: getNextAccount(),
      paymentVaultTokenAccount: getNextAccount(),
      authority: getNextAccount(),
      mint: getNextAccount(),
      userTokenAccount: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getCreatePaymentPoolInstructionDataDecoder().decode(instruction.data),
  };
}
