// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.0.3_@biomejs+biome@1.9.4_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@_3ba448b3ed3117c48cbd10061a84fbfd/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.0.3_@biomejs+biome@1.9.4_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@_3ba448b3ed3117c48cbd10061a84fbfd/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.0.3_@biomejs+biome@1.9.4_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@_3ba448b3ed3117c48cbd10061a84fbfd/node_modules/nuxt/dist/app/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.0.3_@biomejs+biome@1.9.4_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@_3ba448b3ed3117c48cbd10061a84fbfd/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.0.3_@biomejs+biome@1.9.4_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@_3ba448b3ed3117c48cbd10061a84fbfd/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.0.3_@biomejs+biome@1.9.4_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@_3ba448b3ed3117c48cbd10061a84fbfd/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.0.3_@biomejs+biome@1.9.4_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@_3ba448b3ed3117c48cbd10061a84fbfd/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.0.3_@biomejs+biome@1.9.4_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@_3ba448b3ed3117c48cbd10061a84fbfd/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@2.6.3_bufferutil@4.0.9_utf-8-validate@5.0.10_vite@7.1.3_@types+node@22.1_06e02566f55eb6b3bf691723a5f0d9e6/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@2.6.3_bufferutil@4.0.9_utf-8-validate@5.0.10_vite@7.1.3_@types+node@22.1_06e02566f55eb6b3bf691723a5f0d9e6/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.0.3_@biomejs+biome@1.9.4_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@_3ba448b3ed3117c48cbd10061a84fbfd/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.0.3_@biomejs+biome@1.9.4_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@_3ba448b3ed3117c48cbd10061a84fbfd/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
