export const dapps = [
	{
		id: 1,
		group_name: "Delos",
		description:
			"Delos allows anyone to submit a Document and using the amazing Effect Workforce, we categorize the data from the image and validate if it is in fact a useful document.",
		github_url: " https://github.com/jgarciajovel/delos/tree/master ",
		campaign_url: "https://app.effect.network",
		youtube_url: "https://youtu.be/VOw77SIIBHE",
		website_url: "",
		devpost: "",
		image_url: "delos.svg",
		tags: ["identification", "validation"],
		twitter: "",
		discord: "",
		instagram: "",
		reddit: "",
		featured: 1,
	},
	{
		id: 5,
		group_name: "QuickCat",
		description:
			"QuickCat is an app built on Shopify, a platform used by over 1.7M merchants to run their online stores. The goal is to help merchants save time and increase sales by organizing their online product listing with the help of a global human workforce.",
		github_url:
			"https://github.com/effectai/hackathon-submission-repo/tree/main/catalogue",
		campaign_url: "https://testnet.effect.network/campaigns/190",
		youtube_url: "https://youtu.be/9ah7O1HCpcs",
		website_url: "https://apps.shopify.com/quickcat",
		devpost:
			"https://effect-network-hackathon.devpost.com/submissions/293030-catalogue",
		image_url: "quick-cat.svg",
		tags: ["validation", "categorization"],
		twitter: "",
		discord: "",
		instagram: "",
		reddit: "",
		featured: 1,
	},
	{
		id: 11,
		group_name: "secret dapp",
		image_url: "random-1.png",
		discord: "",
		instagram: "",
		reddit: "",
		featured: 1,
	},
	{
		id: 7,
		group_name: "Ask A Stranger",
		description: "Ask any question, and wait for the answer from Effect Force!",
		github_url:
			"https://github.com/effectai/hackathon-submission-repo/tree/main/askastranger",
		campaign_url: "https://testnet.effect.network/campaigns/178",
		youtube_url: "",
		website_url: "https://askastranger.github.io/",
		devpost:
			"https://effect-network-hackathon.devpost.com/submissions/295751-askastranger",
		image_url: "ask-a-stranger.svg",
		tags: ["social"],
		twitter: "",
		discord: "",
		instagram: "",
		reddit: "",
	},
	{
		id: 1,
		group_name: "Kraft Heinz",
		image_url: "kraft_heinz.svg",
		discord: "",
		instagram: "",
		reddit: "",
		featured: 1,
	},
	{
		id: 1,
		group_name: "Git Star",
		discord: "",
		image_url: "gitstar.png",
		instagram: "",
		reddit: "",
		featured: 1,
	},
];
