[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
effect_vesting = "DBTKwjzLfABb1vAX2GijQ6SVDFQPJiBYyHvSXHMFzyHv"
effect_rewards = "BPSquzLynBvygnkRDmE91ShzpL5SNmNjvXi85uRVuJdk"
effect_staking = "5f7WaR7jC3metyDTSq7YGAyq1HfCuoGMUVf9NHP578Dm"
effect_migration = "WkXR6Wnz1wXr48vw18Q8t7GYm9h3JFUXzAJWDjZopK7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./tests/keys/authGiAp86YEPGjqpKNxAMHxqcgvjmBfQkqqvhf7yMV.json"

[workspace]
members = ["programs/effect-migration/program", "programs/effect-staking/program", "programs/effect-rewards/program", "programs/effect-vesting/program"]

[scripts]
test = "npx tsx scripts/export-IDL.ts && pnpm vitest run"

