[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_snapshot_migration = "53ADM5kMezJ6KmgKQpmnngfVSRaYewZVRQ1m1q8gDXvt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
