[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
effect_vesting = "GSzDavs4yP5jqnVTnjjmJ9DJ5yUQ6AB7vBTNv2BBmaSe"
effect_rewards = "HJR3op52N7tNycXqQnVu8cDnxH7udp4pYi1ps9S1hdBz"
effect_staking = "3FPg1CgXQAL6Va3EJ9W14R44cEGqHpATw6ADgkUwSspw"
effect_migration = "BraRBZAVsUaxs46ob4gY5o9JvDHTGppChigyz7qwJm9g"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./tests/keys/authGiAp86YEPGjqpKNxAMHxqcgvjmBfQkqqvhf7yMV.json"

[workspace]
members = ["programs/effect-migration", "programs/effect-staking", "programs/effect-rewards", "programs/effect-vesting"]

[scripts]
deploy_local = "deploy --program-name effect-staking --provider.cluster localnet"
test = "npx tsx scripts/export-IDL.ts && pnpm vitest run"
