[toolchain]

[workspace]
members = [
#    "common",
    "programs/solana-snapshot-migration",
    "programs/effect-staking",
]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_snapshot_migration = "39ZKpaDoLd4Q6g7cQHRmJetUTK2HHcbyZcH4LNR39jCk"
effect_staking = "effScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/tests.ts"
