[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
effect_vesting = "DexJUgYMgjpePPakuMU4aLYuQ7N9ttBEWJs4SPR2hgZr"
effect_rewards = "DA2dSgEzNZ9vHbVwYGp4iLUfNjqBMHG7D7Vk1NdKWbSY"
effect_staking = "6EQ532strjkZpAvqd4JhtJxMppinnDJi7kynvBWut7C2"
effect_migration = "mkBkDyshkoJ3c1TdjNxwM4jUkA6qBbtSQHeMjr4atxH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./tests/keys/authGiAp86YEPGjqpKNxAMHxqcgvjmBfQkqqvhf7yMV.json"

[workspace]
members = ["programs/effect-migration/program", "programs/effect-staking/program", "programs/effect-rewards/program", "programs/effect-vesting/program"]

[scripts]
test = "npx tsx scripts/export-IDL.ts && pnpm vitest run"

