[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
effect_vesting = "EabRXJfYfzbkTTq5546mxDiT5yv2k2rjjN4kY6c4S9Br"
effect_rewards = "AVKZ1LKwV7U5jQPdMev1iQ3rQrcQqzV6AwMfAZwQJomT"
effect_staking = "eR1sM73NpFqq7DSR5YDAgneWW29AZA8sRm1BFakzYpH"
effect_migration = "9hJuxBiFY82YiciAa6wERpHX8s9n1uvzhwaUSFoBJnZD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/effect-migration", "programs/effect-staking", "programs/effect-rewards", "programs/effect-vesting"]

[scripts]
deploy_local = "deploy --program-name effect-staking --provider.cluster localnet"
test = "npx tsx scripts/export-IDL.ts && pnpm vitest run"
