/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { EFFECT_REWARDS_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const CLAIM_DISCRIMINATOR = new Uint8Array([
  62, 198, 214, 193, 213, 159, 108, 210,
]);

export function getClaimDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CLAIM_DISCRIMINATOR);
}

export type ClaimInstruction<
  TProgram extends string = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
  TAccountReflectionAccount extends string | IAccountMeta<string> = string,
  TAccountRewardVaultTokenAccount extends
    | string
    | IAccountMeta<string> = string,
  TAccountStakeAccount extends string | IAccountMeta<string> = string,
  TAccountRewardAccount extends string | IAccountMeta<string> = string,
  TAccountRecipientTokenAccount extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountReflectionAccount extends string
        ? WritableAccount<TAccountReflectionAccount>
        : TAccountReflectionAccount,
      TAccountRewardVaultTokenAccount extends string
        ? WritableAccount<TAccountRewardVaultTokenAccount>
        : TAccountRewardVaultTokenAccount,
      TAccountStakeAccount extends string
        ? WritableAccount<TAccountStakeAccount>
        : TAccountStakeAccount,
      TAccountRewardAccount extends string
        ? WritableAccount<TAccountRewardAccount>
        : TAccountRewardAccount,
      TAccountRecipientTokenAccount extends string
        ? WritableAccount<TAccountRecipientTokenAccount>
        : TAccountRecipientTokenAccount,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimInstructionData = { discriminator: ReadonlyUint8Array };

export type ClaimInstructionDataArgs = {};

export function getClaimInstructionDataEncoder(): Encoder<ClaimInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLAIM_DISCRIMINATOR })
  );
}

export function getClaimInstructionDataDecoder(): Decoder<ClaimInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getClaimInstructionDataCodec(): Codec<
  ClaimInstructionDataArgs,
  ClaimInstructionData
> {
  return combineCodec(
    getClaimInstructionDataEncoder(),
    getClaimInstructionDataDecoder()
  );
}

export type ClaimAsyncInput<
  TAccountReflectionAccount extends string = string,
  TAccountRewardVaultTokenAccount extends string = string,
  TAccountStakeAccount extends string = string,
  TAccountRewardAccount extends string = string,
  TAccountRecipientTokenAccount extends string = string,
  TAccountAuthority extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  reflectionAccount: Address<TAccountReflectionAccount>;
  rewardVaultTokenAccount?: Address<TAccountRewardVaultTokenAccount>;
  stakeAccount: Address<TAccountStakeAccount>;
  rewardAccount?: Address<TAccountRewardAccount>;
  recipientTokenAccount: Address<TAccountRecipientTokenAccount>;
  authority: TransactionSigner<TAccountAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getClaimInstructionAsync<
  TAccountReflectionAccount extends string,
  TAccountRewardVaultTokenAccount extends string,
  TAccountStakeAccount extends string,
  TAccountRewardAccount extends string,
  TAccountRecipientTokenAccount extends string,
  TAccountAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
>(
  input: ClaimAsyncInput<
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountStakeAccount,
    TAccountRewardAccount,
    TAccountRecipientTokenAccount,
    TAccountAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  ClaimInstruction<
    TProgramAddress,
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountStakeAccount,
    TAccountRewardAccount,
    TAccountRecipientTokenAccount,
    TAccountAuthority,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_REWARDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    reflectionAccount: {
      value: input.reflectionAccount ?? null,
      isWritable: true,
    },
    rewardVaultTokenAccount: {
      value: input.rewardVaultTokenAccount ?? null,
      isWritable: true,
    },
    stakeAccount: { value: input.stakeAccount ?? null, isWritable: true },
    rewardAccount: { value: input.rewardAccount ?? null, isWritable: true },
    recipientTokenAccount: {
      value: input.recipientTokenAccount ?? null,
      isWritable: true,
    },
    authority: { value: input.authority ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.rewardVaultTokenAccount.value) {
    accounts.rewardVaultTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.reflectionAccount.value)
        ),
      ],
    });
  }
  if (!accounts.rewardAccount.value) {
    accounts.rewardAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.stakeAccount.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.reflectionAccount),
      getAccountMeta(accounts.rewardVaultTokenAccount),
      getAccountMeta(accounts.stakeAccount),
      getAccountMeta(accounts.rewardAccount),
      getAccountMeta(accounts.recipientTokenAccount),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getClaimInstructionDataEncoder().encode({}),
  } as ClaimInstruction<
    TProgramAddress,
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountStakeAccount,
    TAccountRewardAccount,
    TAccountRecipientTokenAccount,
    TAccountAuthority,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ClaimInput<
  TAccountReflectionAccount extends string = string,
  TAccountRewardVaultTokenAccount extends string = string,
  TAccountStakeAccount extends string = string,
  TAccountRewardAccount extends string = string,
  TAccountRecipientTokenAccount extends string = string,
  TAccountAuthority extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  reflectionAccount: Address<TAccountReflectionAccount>;
  rewardVaultTokenAccount: Address<TAccountRewardVaultTokenAccount>;
  stakeAccount: Address<TAccountStakeAccount>;
  rewardAccount: Address<TAccountRewardAccount>;
  recipientTokenAccount: Address<TAccountRecipientTokenAccount>;
  authority: TransactionSigner<TAccountAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getClaimInstruction<
  TAccountReflectionAccount extends string,
  TAccountRewardVaultTokenAccount extends string,
  TAccountStakeAccount extends string,
  TAccountRewardAccount extends string,
  TAccountRecipientTokenAccount extends string,
  TAccountAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
>(
  input: ClaimInput<
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountStakeAccount,
    TAccountRewardAccount,
    TAccountRecipientTokenAccount,
    TAccountAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): ClaimInstruction<
  TProgramAddress,
  TAccountReflectionAccount,
  TAccountRewardVaultTokenAccount,
  TAccountStakeAccount,
  TAccountRewardAccount,
  TAccountRecipientTokenAccount,
  TAccountAuthority,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_REWARDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    reflectionAccount: {
      value: input.reflectionAccount ?? null,
      isWritable: true,
    },
    rewardVaultTokenAccount: {
      value: input.rewardVaultTokenAccount ?? null,
      isWritable: true,
    },
    stakeAccount: { value: input.stakeAccount ?? null, isWritable: true },
    rewardAccount: { value: input.rewardAccount ?? null, isWritable: true },
    recipientTokenAccount: {
      value: input.recipientTokenAccount ?? null,
      isWritable: true,
    },
    authority: { value: input.authority ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.reflectionAccount),
      getAccountMeta(accounts.rewardVaultTokenAccount),
      getAccountMeta(accounts.stakeAccount),
      getAccountMeta(accounts.rewardAccount),
      getAccountMeta(accounts.recipientTokenAccount),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getClaimInstructionDataEncoder().encode({}),
  } as ClaimInstruction<
    TProgramAddress,
    TAccountReflectionAccount,
    TAccountRewardVaultTokenAccount,
    TAccountStakeAccount,
    TAccountRewardAccount,
    TAccountRecipientTokenAccount,
    TAccountAuthority,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ParsedClaimInstruction<
  TProgram extends string = typeof EFFECT_REWARDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    reflectionAccount: TAccountMetas[0];
    rewardVaultTokenAccount: TAccountMetas[1];
    stakeAccount: TAccountMetas[2];
    rewardAccount: TAccountMetas[3];
    recipientTokenAccount: TAccountMetas[4];
    authority: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
  };
  data: ClaimInstructionData;
};

export function parseClaimInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedClaimInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      reflectionAccount: getNextAccount(),
      rewardVaultTokenAccount: getNextAccount(),
      stakeAccount: getNextAccount(),
      rewardAccount: getNextAccount(),
      recipientTokenAccount: getNextAccount(),
      authority: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getClaimInstructionDataDecoder().decode(instruction.data),
  };
}
