/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { EFFECT_MIGRATION_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const CREATE_STAKE_CLAIM_DISCRIMINATOR = new Uint8Array([
  209, 124, 209, 232, 131, 66, 118, 116,
]);

export function getCreateStakeClaimDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_STAKE_CLAIM_DISCRIMINATOR
  );
}

export type CreateStakeClaimInstruction<
  TProgram extends string = typeof EFFECT_MIGRATION_PROGRAM_ADDRESS,
  TAccountMigrationAccount extends string | IAccountMeta<string> = string,
  TAccountClaimVaultTokenAccount extends string | IAccountMeta<string> = string,
  TAccountMint extends string | IAccountMeta<string> = string,
  TAccountAuthority extends
    | string
    | IAccountMeta<string> = 'authGiAp86YEPGjqpKNxAMHxqcgvjmBfQkqqvhf7yMV',
  TAccountUserTokenAccount extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountRent extends
    | string
    | IAccountMeta<string> = 'SysvarRent111111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountMigrationAccount extends string
        ? WritableAccount<TAccountMigrationAccount>
        : TAccountMigrationAccount,
      TAccountClaimVaultTokenAccount extends string
        ? WritableAccount<TAccountClaimVaultTokenAccount>
        : TAccountClaimVaultTokenAccount,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountUserTokenAccount extends string
        ? WritableAccount<TAccountUserTokenAccount>
        : TAccountUserTokenAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts,
    ]
  >;

export type CreateStakeClaimInstructionData = {
  discriminator: ReadonlyUint8Array;
  foreignAddress: ReadonlyUint8Array;
  stakeStartTime: bigint;
  amount: bigint;
};

export type CreateStakeClaimInstructionDataArgs = {
  foreignAddress: ReadonlyUint8Array;
  stakeStartTime: number | bigint;
  amount: number | bigint;
};

export function getCreateStakeClaimInstructionDataEncoder(): Encoder<CreateStakeClaimInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      [
        'foreignAddress',
        addEncoderSizePrefix(getBytesEncoder(), getU32Encoder()),
      ],
      ['stakeStartTime', getI64Encoder()],
      ['amount', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CREATE_STAKE_CLAIM_DISCRIMINATOR })
  );
}

export function getCreateStakeClaimInstructionDataDecoder(): Decoder<CreateStakeClaimInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    [
      'foreignAddress',
      addDecoderSizePrefix(getBytesDecoder(), getU32Decoder()),
    ],
    ['stakeStartTime', getI64Decoder()],
    ['amount', getU64Decoder()],
  ]);
}

export function getCreateStakeClaimInstructionDataCodec(): Codec<
  CreateStakeClaimInstructionDataArgs,
  CreateStakeClaimInstructionData
> {
  return combineCodec(
    getCreateStakeClaimInstructionDataEncoder(),
    getCreateStakeClaimInstructionDataDecoder()
  );
}

export type CreateStakeClaimAsyncInput<
  TAccountMigrationAccount extends string = string,
  TAccountClaimVaultTokenAccount extends string = string,
  TAccountMint extends string = string,
  TAccountAuthority extends string = string,
  TAccountUserTokenAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  migrationAccount?: Address<TAccountMigrationAccount>;
  claimVaultTokenAccount?: Address<TAccountClaimVaultTokenAccount>;
  mint: Address<TAccountMint>;
  authority?: TransactionSigner<TAccountAuthority>;
  userTokenAccount: Address<TAccountUserTokenAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
  foreignAddress: CreateStakeClaimInstructionDataArgs['foreignAddress'];
  stakeStartTime: CreateStakeClaimInstructionDataArgs['stakeStartTime'];
  amount: CreateStakeClaimInstructionDataArgs['amount'];
};

export async function getCreateStakeClaimInstructionAsync<
  TAccountMigrationAccount extends string,
  TAccountClaimVaultTokenAccount extends string,
  TAccountMint extends string,
  TAccountAuthority extends string,
  TAccountUserTokenAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof EFFECT_MIGRATION_PROGRAM_ADDRESS,
>(
  input: CreateStakeClaimAsyncInput<
    TAccountMigrationAccount,
    TAccountClaimVaultTokenAccount,
    TAccountMint,
    TAccountAuthority,
    TAccountUserTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  CreateStakeClaimInstruction<
    TProgramAddress,
    TAccountMigrationAccount,
    TAccountClaimVaultTokenAccount,
    TAccountMint,
    TAccountAuthority,
    TAccountUserTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_MIGRATION_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    migrationAccount: {
      value: input.migrationAccount ?? null,
      isWritable: true,
    },
    claimVaultTokenAccount: {
      value: input.claimVaultTokenAccount ?? null,
      isWritable: true,
    },
    mint: { value: input.mint ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: true },
    userTokenAccount: {
      value: input.userTokenAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.migrationAccount.value) {
    accounts.migrationAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
        addEncoderSizePrefix(getBytesEncoder(), getU32Encoder()).encode(
          expectSome(args.foreignAddress)
        ),
      ],
    });
  }
  if (!accounts.claimVaultTokenAccount.value) {
    accounts.claimVaultTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.migrationAccount.value)
        ),
      ],
    });
  }
  if (!accounts.authority.value) {
    accounts.authority.value =
      'authGiAp86YEPGjqpKNxAMHxqcgvjmBfQkqqvhf7yMV' as Address<'authGiAp86YEPGjqpKNxAMHxqcgvjmBfQkqqvhf7yMV'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      'SysvarRent111111111111111111111111111111111' as Address<'SysvarRent111111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.migrationAccount),
      getAccountMeta(accounts.claimVaultTokenAccount),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.userTokenAccount),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.rent),
    ],
    programAddress,
    data: getCreateStakeClaimInstructionDataEncoder().encode(
      args as CreateStakeClaimInstructionDataArgs
    ),
  } as CreateStakeClaimInstruction<
    TProgramAddress,
    TAccountMigrationAccount,
    TAccountClaimVaultTokenAccount,
    TAccountMint,
    TAccountAuthority,
    TAccountUserTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >;

  return instruction;
}

export type CreateStakeClaimInput<
  TAccountMigrationAccount extends string = string,
  TAccountClaimVaultTokenAccount extends string = string,
  TAccountMint extends string = string,
  TAccountAuthority extends string = string,
  TAccountUserTokenAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string,
> = {
  migrationAccount: Address<TAccountMigrationAccount>;
  claimVaultTokenAccount: Address<TAccountClaimVaultTokenAccount>;
  mint: Address<TAccountMint>;
  authority?: TransactionSigner<TAccountAuthority>;
  userTokenAccount: Address<TAccountUserTokenAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
  foreignAddress: CreateStakeClaimInstructionDataArgs['foreignAddress'];
  stakeStartTime: CreateStakeClaimInstructionDataArgs['stakeStartTime'];
  amount: CreateStakeClaimInstructionDataArgs['amount'];
};

export function getCreateStakeClaimInstruction<
  TAccountMigrationAccount extends string,
  TAccountClaimVaultTokenAccount extends string,
  TAccountMint extends string,
  TAccountAuthority extends string,
  TAccountUserTokenAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof EFFECT_MIGRATION_PROGRAM_ADDRESS,
>(
  input: CreateStakeClaimInput<
    TAccountMigrationAccount,
    TAccountClaimVaultTokenAccount,
    TAccountMint,
    TAccountAuthority,
    TAccountUserTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress }
): CreateStakeClaimInstruction<
  TProgramAddress,
  TAccountMigrationAccount,
  TAccountClaimVaultTokenAccount,
  TAccountMint,
  TAccountAuthority,
  TAccountUserTokenAccount,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountRent
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_MIGRATION_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    migrationAccount: {
      value: input.migrationAccount ?? null,
      isWritable: true,
    },
    claimVaultTokenAccount: {
      value: input.claimVaultTokenAccount ?? null,
      isWritable: true,
    },
    mint: { value: input.mint ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: true },
    userTokenAccount: {
      value: input.userTokenAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.authority.value) {
    accounts.authority.value =
      'authGiAp86YEPGjqpKNxAMHxqcgvjmBfQkqqvhf7yMV' as Address<'authGiAp86YEPGjqpKNxAMHxqcgvjmBfQkqqvhf7yMV'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      'SysvarRent111111111111111111111111111111111' as Address<'SysvarRent111111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.migrationAccount),
      getAccountMeta(accounts.claimVaultTokenAccount),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.userTokenAccount),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.rent),
    ],
    programAddress,
    data: getCreateStakeClaimInstructionDataEncoder().encode(
      args as CreateStakeClaimInstructionDataArgs
    ),
  } as CreateStakeClaimInstruction<
    TProgramAddress,
    TAccountMigrationAccount,
    TAccountClaimVaultTokenAccount,
    TAccountMint,
    TAccountAuthority,
    TAccountUserTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >;

  return instruction;
}

export type ParsedCreateStakeClaimInstruction<
  TProgram extends string = typeof EFFECT_MIGRATION_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    migrationAccount: TAccountMetas[0];
    claimVaultTokenAccount: TAccountMetas[1];
    mint: TAccountMetas[2];
    authority: TAccountMetas[3];
    userTokenAccount: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
    rent: TAccountMetas[7];
  };
  data: CreateStakeClaimInstructionData;
};

export function parseCreateStakeClaimInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedCreateStakeClaimInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      migrationAccount: getNextAccount(),
      claimVaultTokenAccount: getNextAccount(),
      mint: getNextAccount(),
      authority: getNextAccount(),
      userTokenAccount: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getCreateStakeClaimInstructionDataDecoder().decode(instruction.data),
  };
}
