export const availableCapabilities = [
  {
    icon: "i-lucide-mic",
    id: "effectai/capability-microphone-access:0.0.1",
    href: "capabilities/microphone",
    name: "Microphone Access",
    category: "Hardware",
    description: "Access to microphone for audio processing tasks",
    cost: 50,
    estimatedEarnings: 800,
    tags: ["Audio", "Processing", "Hardware"],
  },
  {
    icon: "i-lucide-book-open",
    id: "effectai/capability-english-language:0.0.1",
    href: "capabilities/language-english",
    name: "English Language",
    category: "Language",
    description: "Proficient in English language tasks",
    cost: 30,
    estimatedEarnings: 500,
    tags: ["Language", "English", "Communication"],
  },
  {
    icon: "i-lucide-wifi",
    id: "effectai/capability-high-speed-internet:0.0.1",
    name: "High-Speed Internet",
    category: "Network",
    description: "Reliable high-speed internet connection",
    cost: 100,
    estimatedEarnings: 1500,
    tags: ["Network", "Internet", "Speed"],
  },
];
