/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { EFFECT_PAYMENT_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';
import {
  getProofDataDecoder,
  getProofDataEncoder,
  type ProofData,
  type ProofDataArgs,
} from '../types';

export const CLAIM_PROOFS_DISCRIMINATOR = new Uint8Array([
  83, 214, 0, 81, 196, 54, 192, 8,
]);

export function getClaimProofsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLAIM_PROOFS_DISCRIMINATOR
  );
}

export type ClaimProofsInstruction<
  TProgram extends string = typeof EFFECT_PAYMENT_PROGRAM_ADDRESS,
  TAccountPaymentAccount extends string | IAccountMeta<string> = string,
  TAccountPaymentVaultTokenAccount extends
    | string
    | IAccountMeta<string> = string,
  TAccountRecipientTokenAccount extends string | IAccountMeta<string> = string,
  TAccountRecipientManagerDataAccount extends
    | string
    | IAccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountMint extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountPaymentAccount extends string
        ? ReadonlyAccount<TAccountPaymentAccount>
        : TAccountPaymentAccount,
      TAccountPaymentVaultTokenAccount extends string
        ? WritableAccount<TAccountPaymentVaultTokenAccount>
        : TAccountPaymentVaultTokenAccount,
      TAccountRecipientTokenAccount extends string
        ? WritableAccount<TAccountRecipientTokenAccount>
        : TAccountRecipientTokenAccount,
      TAccountRecipientManagerDataAccount extends string
        ? WritableAccount<TAccountRecipientManagerDataAccount>
        : TAccountRecipientManagerDataAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimProofsInstructionData = {
  discriminator: ReadonlyUint8Array;
  pubX: ReadonlyUint8Array;
  pubY: ReadonlyUint8Array;
  proofData: Array<ProofData>;
};

export type ClaimProofsInstructionDataArgs = {
  pubX: ReadonlyUint8Array;
  pubY: ReadonlyUint8Array;
  proofData: Array<ProofDataArgs>;
};

export function getClaimProofsInstructionDataEncoder(): Encoder<ClaimProofsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['pubX', fixEncoderSize(getBytesEncoder(), 32)],
      ['pubY', fixEncoderSize(getBytesEncoder(), 32)],
      ['proofData', getArrayEncoder(getProofDataEncoder())],
    ]),
    (value) => ({ ...value, discriminator: CLAIM_PROOFS_DISCRIMINATOR })
  );
}

export function getClaimProofsInstructionDataDecoder(): Decoder<ClaimProofsInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['pubX', fixDecoderSize(getBytesDecoder(), 32)],
    ['pubY', fixDecoderSize(getBytesDecoder(), 32)],
    ['proofData', getArrayDecoder(getProofDataDecoder())],
  ]);
}

export function getClaimProofsInstructionDataCodec(): Codec<
  ClaimProofsInstructionDataArgs,
  ClaimProofsInstructionData
> {
  return combineCodec(
    getClaimProofsInstructionDataEncoder(),
    getClaimProofsInstructionDataDecoder()
  );
}

export type ClaimProofsAsyncInput<
  TAccountPaymentAccount extends string = string,
  TAccountPaymentVaultTokenAccount extends string = string,
  TAccountRecipientTokenAccount extends string = string,
  TAccountRecipientManagerDataAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountMint extends string = string,
  TAccountAuthority extends string = string,
> = {
  paymentAccount: Address<TAccountPaymentAccount>;
  paymentVaultTokenAccount?: Address<TAccountPaymentVaultTokenAccount>;
  recipientTokenAccount: Address<TAccountRecipientTokenAccount>;
  recipientManagerDataAccount: Address<TAccountRecipientManagerDataAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  mint: Address<TAccountMint>;
  authority: TransactionSigner<TAccountAuthority>;
  pubX: ClaimProofsInstructionDataArgs['pubX'];
  pubY: ClaimProofsInstructionDataArgs['pubY'];
  proofData: ClaimProofsInstructionDataArgs['proofData'];
};

export async function getClaimProofsInstructionAsync<
  TAccountPaymentAccount extends string,
  TAccountPaymentVaultTokenAccount extends string,
  TAccountRecipientTokenAccount extends string,
  TAccountRecipientManagerDataAccount extends string,
  TAccountTokenProgram extends string,
  TAccountMint extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof EFFECT_PAYMENT_PROGRAM_ADDRESS,
>(
  input: ClaimProofsAsyncInput<
    TAccountPaymentAccount,
    TAccountPaymentVaultTokenAccount,
    TAccountRecipientTokenAccount,
    TAccountRecipientManagerDataAccount,
    TAccountTokenProgram,
    TAccountMint,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  ClaimProofsInstruction<
    TProgramAddress,
    TAccountPaymentAccount,
    TAccountPaymentVaultTokenAccount,
    TAccountRecipientTokenAccount,
    TAccountRecipientManagerDataAccount,
    TAccountTokenProgram,
    TAccountMint,
    TAccountAuthority
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_PAYMENT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    paymentAccount: { value: input.paymentAccount ?? null, isWritable: false },
    paymentVaultTokenAccount: {
      value: input.paymentVaultTokenAccount ?? null,
      isWritable: true,
    },
    recipientTokenAccount: {
      value: input.recipientTokenAccount ?? null,
      isWritable: true,
    },
    recipientManagerDataAccount: {
      value: input.recipientManagerDataAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.paymentVaultTokenAccount.value) {
    accounts.paymentVaultTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.paymentAccount.value)
        ),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.paymentAccount),
      getAccountMeta(accounts.paymentVaultTokenAccount),
      getAccountMeta(accounts.recipientTokenAccount),
      getAccountMeta(accounts.recipientManagerDataAccount),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getClaimProofsInstructionDataEncoder().encode(
      args as ClaimProofsInstructionDataArgs
    ),
  } as ClaimProofsInstruction<
    TProgramAddress,
    TAccountPaymentAccount,
    TAccountPaymentVaultTokenAccount,
    TAccountRecipientTokenAccount,
    TAccountRecipientManagerDataAccount,
    TAccountTokenProgram,
    TAccountMint,
    TAccountAuthority
  >;

  return instruction;
}

export type ClaimProofsInput<
  TAccountPaymentAccount extends string = string,
  TAccountPaymentVaultTokenAccount extends string = string,
  TAccountRecipientTokenAccount extends string = string,
  TAccountRecipientManagerDataAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountMint extends string = string,
  TAccountAuthority extends string = string,
> = {
  paymentAccount: Address<TAccountPaymentAccount>;
  paymentVaultTokenAccount: Address<TAccountPaymentVaultTokenAccount>;
  recipientTokenAccount: Address<TAccountRecipientTokenAccount>;
  recipientManagerDataAccount: Address<TAccountRecipientManagerDataAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  mint: Address<TAccountMint>;
  authority: TransactionSigner<TAccountAuthority>;
  pubX: ClaimProofsInstructionDataArgs['pubX'];
  pubY: ClaimProofsInstructionDataArgs['pubY'];
  proofData: ClaimProofsInstructionDataArgs['proofData'];
};

export function getClaimProofsInstruction<
  TAccountPaymentAccount extends string,
  TAccountPaymentVaultTokenAccount extends string,
  TAccountRecipientTokenAccount extends string,
  TAccountRecipientManagerDataAccount extends string,
  TAccountTokenProgram extends string,
  TAccountMint extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof EFFECT_PAYMENT_PROGRAM_ADDRESS,
>(
  input: ClaimProofsInput<
    TAccountPaymentAccount,
    TAccountPaymentVaultTokenAccount,
    TAccountRecipientTokenAccount,
    TAccountRecipientManagerDataAccount,
    TAccountTokenProgram,
    TAccountMint,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): ClaimProofsInstruction<
  TProgramAddress,
  TAccountPaymentAccount,
  TAccountPaymentVaultTokenAccount,
  TAccountRecipientTokenAccount,
  TAccountRecipientManagerDataAccount,
  TAccountTokenProgram,
  TAccountMint,
  TAccountAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_PAYMENT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    paymentAccount: { value: input.paymentAccount ?? null, isWritable: false },
    paymentVaultTokenAccount: {
      value: input.paymentVaultTokenAccount ?? null,
      isWritable: true,
    },
    recipientTokenAccount: {
      value: input.recipientTokenAccount ?? null,
      isWritable: true,
    },
    recipientManagerDataAccount: {
      value: input.recipientManagerDataAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.paymentAccount),
      getAccountMeta(accounts.paymentVaultTokenAccount),
      getAccountMeta(accounts.recipientTokenAccount),
      getAccountMeta(accounts.recipientManagerDataAccount),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getClaimProofsInstructionDataEncoder().encode(
      args as ClaimProofsInstructionDataArgs
    ),
  } as ClaimProofsInstruction<
    TProgramAddress,
    TAccountPaymentAccount,
    TAccountPaymentVaultTokenAccount,
    TAccountRecipientTokenAccount,
    TAccountRecipientManagerDataAccount,
    TAccountTokenProgram,
    TAccountMint,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedClaimProofsInstruction<
  TProgram extends string = typeof EFFECT_PAYMENT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    paymentAccount: TAccountMetas[0];
    paymentVaultTokenAccount: TAccountMetas[1];
    recipientTokenAccount: TAccountMetas[2];
    recipientManagerDataAccount: TAccountMetas[3];
    tokenProgram: TAccountMetas[4];
    mint: TAccountMetas[5];
    authority: TAccountMetas[6];
  };
  data: ClaimProofsInstructionData;
};

export function parseClaimProofsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedClaimProofsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      paymentAccount: getNextAccount(),
      paymentVaultTokenAccount: getNextAccount(),
      recipientTokenAccount: getNextAccount(),
      recipientManagerDataAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
      mint: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getClaimProofsInstructionDataDecoder().decode(instruction.data),
  };
}
