[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
storage = { path = "../storage" }
proto = { path = "../proto" }
anyhow = "1"
serde_json = "1"
workflow = { path = "../workflow" }
domain = { path = "../domain" }
