/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { EFFECT_VESTING_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const CLOSE_DISCRIMINATOR = new Uint8Array([
  98, 165, 201, 177, 108, 65, 206, 96,
]);

export function getCloseDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CLOSE_DISCRIMINATOR);
}

export type CloseInstruction<
  TProgram extends string = typeof EFFECT_VESTING_PROGRAM_ADDRESS,
  TAccountVestingAccount extends string | AccountMeta<string> = string,
  TAccountVestingVaultTokenAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountRecipientTokenAccount extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountVestingAccount extends string
        ? WritableAccount<TAccountVestingAccount>
        : TAccountVestingAccount,
      TAccountVestingVaultTokenAccount extends string
        ? WritableAccount<TAccountVestingVaultTokenAccount>
        : TAccountVestingVaultTokenAccount,
      TAccountRecipientTokenAccount extends string
        ? WritableAccount<TAccountRecipientTokenAccount>
        : TAccountRecipientTokenAccount,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CloseInstructionData = { discriminator: ReadonlyUint8Array };

export type CloseInstructionDataArgs = {};

export function getCloseInstructionDataEncoder(): FixedSizeEncoder<CloseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLOSE_DISCRIMINATOR })
  );
}

export function getCloseInstructionDataDecoder(): FixedSizeDecoder<CloseInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCloseInstructionDataCodec(): FixedSizeCodec<
  CloseInstructionDataArgs,
  CloseInstructionData
> {
  return combineCodec(
    getCloseInstructionDataEncoder(),
    getCloseInstructionDataDecoder()
  );
}

export type CloseAsyncInput<
  TAccountVestingAccount extends string = string,
  TAccountVestingVaultTokenAccount extends string = string,
  TAccountRecipientTokenAccount extends string = string,
  TAccountAuthority extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  vestingAccount: Address<TAccountVestingAccount>;
  vestingVaultTokenAccount?: Address<TAccountVestingVaultTokenAccount>;
  recipientTokenAccount: Address<TAccountRecipientTokenAccount>;
  authority: TransactionSigner<TAccountAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getCloseInstructionAsync<
  TAccountVestingAccount extends string,
  TAccountVestingVaultTokenAccount extends string,
  TAccountRecipientTokenAccount extends string,
  TAccountAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof EFFECT_VESTING_PROGRAM_ADDRESS,
>(
  input: CloseAsyncInput<
    TAccountVestingAccount,
    TAccountVestingVaultTokenAccount,
    TAccountRecipientTokenAccount,
    TAccountAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  CloseInstruction<
    TProgramAddress,
    TAccountVestingAccount,
    TAccountVestingVaultTokenAccount,
    TAccountRecipientTokenAccount,
    TAccountAuthority,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_VESTING_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vestingAccount: { value: input.vestingAccount ?? null, isWritable: true },
    vestingVaultTokenAccount: {
      value: input.vestingVaultTokenAccount ?? null,
      isWritable: true,
    },
    recipientTokenAccount: {
      value: input.recipientTokenAccount ?? null,
      isWritable: true,
    },
    authority: { value: input.authority ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.vestingVaultTokenAccount.value) {
    accounts.vestingVaultTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.vestingAccount.value)
        ),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.vestingAccount),
      getAccountMeta(accounts.vestingVaultTokenAccount),
      getAccountMeta(accounts.recipientTokenAccount),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getCloseInstructionDataEncoder().encode({}),
  } as CloseInstruction<
    TProgramAddress,
    TAccountVestingAccount,
    TAccountVestingVaultTokenAccount,
    TAccountRecipientTokenAccount,
    TAccountAuthority,
    TAccountTokenProgram
  >;

  return instruction;
}

export type CloseInput<
  TAccountVestingAccount extends string = string,
  TAccountVestingVaultTokenAccount extends string = string,
  TAccountRecipientTokenAccount extends string = string,
  TAccountAuthority extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  vestingAccount: Address<TAccountVestingAccount>;
  vestingVaultTokenAccount: Address<TAccountVestingVaultTokenAccount>;
  recipientTokenAccount: Address<TAccountRecipientTokenAccount>;
  authority: TransactionSigner<TAccountAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getCloseInstruction<
  TAccountVestingAccount extends string,
  TAccountVestingVaultTokenAccount extends string,
  TAccountRecipientTokenAccount extends string,
  TAccountAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof EFFECT_VESTING_PROGRAM_ADDRESS,
>(
  input: CloseInput<
    TAccountVestingAccount,
    TAccountVestingVaultTokenAccount,
    TAccountRecipientTokenAccount,
    TAccountAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CloseInstruction<
  TProgramAddress,
  TAccountVestingAccount,
  TAccountVestingVaultTokenAccount,
  TAccountRecipientTokenAccount,
  TAccountAuthority,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EFFECT_VESTING_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vestingAccount: { value: input.vestingAccount ?? null, isWritable: true },
    vestingVaultTokenAccount: {
      value: input.vestingVaultTokenAccount ?? null,
      isWritable: true,
    },
    recipientTokenAccount: {
      value: input.recipientTokenAccount ?? null,
      isWritable: true,
    },
    authority: { value: input.authority ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.vestingAccount),
      getAccountMeta(accounts.vestingVaultTokenAccount),
      getAccountMeta(accounts.recipientTokenAccount),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getCloseInstructionDataEncoder().encode({}),
  } as CloseInstruction<
    TProgramAddress,
    TAccountVestingAccount,
    TAccountVestingVaultTokenAccount,
    TAccountRecipientTokenAccount,
    TAccountAuthority,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ParsedCloseInstruction<
  TProgram extends string = typeof EFFECT_VESTING_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vestingAccount: TAccountMetas[0];
    vestingVaultTokenAccount: TAccountMetas[1];
    recipientTokenAccount: TAccountMetas[2];
    authority: TAccountMetas[3];
    tokenProgram: TAccountMetas[4];
  };
  data: CloseInstructionData;
};

export function parseCloseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCloseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      vestingAccount: getNextAccount(),
      vestingVaultTokenAccount: getNextAccount(),
      recipientTokenAccount: getNextAccount(),
      authority: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getCloseInstructionDataDecoder().decode(instruction.data),
  };
}
